### ISSUE TITLE
Add api for text to speech

### ISSUE THREAD

**Issue by r0ld3x** [r0ld3x/text-to-speech#1]
Currently it uses default SpeechSynthesis API of javascript.

change it to external apis like gtts, elevenlabs etc.

**Comment by Ryrahul** [comment]
Are you sure you want to use elevenlabs? I can do it for you but free version of elevenlabs is not good. 
![image](https://github.com/r0ld3x/text-to-speech/assets/121729670/e86f62c6-c279-4253-a9a7-cc1478ad693e)
This is what you will be getting. I can still write the code for elevenlabs if you want

**Comment by r0ld3x** [comment]
> Are you sure you want to use elevenlabs? I can do it for you but free version of elevenlabs is not good. 
> ![image](https://github.com/r0ld3x/text-to-speech/assets/121729670/e86f62c6-c279-4253-a9a7-cc1478ad693e)
> This is what you will be getting. 

I had eleven labs premium but it's expired now

**Comment by Ryrahul** [comment]
So what you want to do? Shall i write the code for it? You would need the api key from a premium account to use it ig or even for google text-to-speech you would need a subscription . I do have google cloud subscription remainig for 5-6 days and its working using that key but again the problem would be other wont be able to use it unless you dont have a premium account

**Comment by r0ld3x** [comment]
> So what you want to do? Shall i write the code for it? You would need the api key from a premium account to use it ig or even for google text-to-speech you would need a subscription . I do have google cloud subscription remainig for 5-6 days and its working using that key but again the problem would be other wont be able to use it unless you dont have a premium account


Make an flask api using gtts library and return audio from api then show it here. 

Good idea right?

**Comment by Ryrahul** [comment]
Yeah i am done with it . Shall i make  a PR

**Comment by Ryrahul** [comment]
@r0ld3x  check #2

**Comment by Ryrahul** [comment]
@r0ld3x  can you also label the pr as hactober fest accepted o hactoberfest

**Comment by r0ld3x** [comment]
> @r0ld3x can you also label the pr as hactober fest accepted o hactoberfest

yes
